#!/usr/bin/env python
# coding: utf-8
"""
Bits the tests share.

The main job here is finding OpenSCAD.  On a developer's machine it may be
installed normally and sit on the PATH.  On a classroom machine it will not
be installed at all -- it lives in assets/bin next to the app.  The tests
look in both places, so they work either way and nobody has to install
anything to run them.
"""

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent.parent
BIN = APP_DIR / "assets" / "bin"


def find_openscad():
    """The OpenSCAD to test with: the bundled one first, then the PATH."""
    for candidate in (BIN / "openscad.exe", BIN / "openscad"):
        if candidate.exists():
            return candidate
    found = shutil.which("openscad") or shutil.which("openscad.exe")
    return Path(found) if found else None


def find_slicer():
    """The real PrusaSlicer, if it is here.  None if it is not."""
    for candidate in (BIN / "prusa-slicer-console.exe",
                      BIN / "prusa-slicer-console",
                      BIN / "prusa-slicer"):
        if candidate.exists():
            return candidate
    found = shutil.which("prusa-slicer-console") or shutil.which("prusa-slicer")
    return Path(found) if found else None


def with_bin_on_path():
    """
    PrusaSlicer and OpenSCAD load their DLLs from the folder they sit in.
    Without this they start and die with no message, which is exactly the
    failure the app itself guards against, so the tests must guard too.
    """
    if BIN.exists() and str(BIN) not in os.environ.get("PATH", ""):
        os.environ["PATH"] = os.environ.get("PATH", "") + os.pathsep + str(BIN)


OPENSCAD = find_openscad()
SLICER = find_slicer()
with_bin_on_path()


# ---------------------------------------------------------------------------
# The stand-in slicer
# ---------------------------------------------------------------------------

STUB_SLICER = r'''#!/usr/bin/env python3
"""A stand-in for PrusaSlicer, so sessions can be tested with no printer."""
import sys

args = sys.argv[1:]

if "--info" in args:
    print("size_x = 40")
    print("size_y = 20")
    print("size_z = 10")
    sys.exit(0)

out = args[args.index("--output") + 1] if "--output" in args else "out.gcode"
with open(out, "w") as handle:
    handle.write(
        "; generated by a stand-in slicer\n"
        "; estimated printing time (normal mode) = 1h 12m 30s\n"
        "; filament used [g] = 14.62\n"
        "; filament used [mm] = 4900.3\n"
        "; total layers count = 100\n")
sys.exit(0)
'''


def make_stub_slicer(folder):
    """
    Write the stand-in and give back a command that runs it.

    A command, not a path: on Windows a .py file cannot be started as a
    program, so it has to be handed to Python.  printing.as_command accepts
    either form, which is what makes this work on both.
    """
    script = Path(folder) / "stub_slicer.py"
    script.write_text(STUB_SLICER, encoding="utf-8")
    if os.name != "nt":
        script.chmod(script.stat().st_mode | 0o111)
    return [sys.executable, str(script)]


# ---------------------------------------------------------------------------

def compile_scad(scad_text, timeout=180):
    """Run OpenSCAD on some code.  Returns (ok, message, size_of_stl)."""
    with tempfile.TemporaryDirectory() as folder:
        scad = Path(folder) / "m.scad"
        stl = Path(folder) / "m.stl"
        scad.write_text(scad_text, encoding="utf-8")
        try:
            result = subprocess.run([str(OPENSCAD), "-o", str(stl), str(scad)],
                                    capture_output=True, text=True,
                                    timeout=timeout)
        except subprocess.TimeoutExpired:
            return False, "OpenSCAD took too long.", 0
        size = stl.stat().st_size if stl.exists() else 0
        return result.returncode == 0 and size > 0, result.stderr, size
